# Run rustfmt with this config (it should be picked up automatically).
use_small_heuristics = "Max"
merge_derives = false
max_width = 110

# run `cargo +nightly fmt` with these uncommented occasionally until it stabilizes
# unstable_features = true
# imports_granularity = "Module"
